---
apiVersion: v1
kind: Service
metadata:
  name: saas-customer-portal
  labels:
    app: saas-customer-portal
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: saas-customer-portal-tls
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: saas-customer-portal
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: saas-customer-portal-metrics
  labels:
    app: saas-customer-portal
    monitoring: prometheus
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: http
      protocol: TCP
  selector:
    app: saas-customer-portal
